-- MySQL Script generated by MySQL Workbench
-- Sat Jan  4 19:43:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@ UNIQUE_CHECKS, UNIQUE_CHECKS = 0;

SET @OLD_FOREIGN_KEY_CHECKS = @@ FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;

SET @OLD_SQL_MODE = @@ SQL_MODE, SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fitness_center` DEFAULT CHARACTER
SET utf8;

USE `fitness_center`;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_center`.`client`(`id` int NOT NULL AUTO_INCREMENT, `firstName` varchar(15) NOT NULL, `lastName` varchar(15) NOT NULL, `phone` varchar(15) NOT NULL, `email` varchar(20) NOT NULL, `password` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_center`.`trainer`(`id` int NOT NULL AUTO_INCREMENT, `firstName` varchar(15) NOT NULL, `lastName` varchar(15) NOT NULL, `phone` varchar(15) NOT NULL, `speciality` varchar(25) NOT NULL, PRIMARY KEY (`id`)) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`hall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_center`.`hall`(`id` int NOT NULL AUTO_INCREMENT, `name` varchar(25) NOT NULL, `capacity` int NOT NULL, PRIMARY KEY (`id`)) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_center`.`class`(`id` int NOT NULL AUTO_INCREMENT, `name` varchar(45) NOT NULL, `duration` DECIMAL(1, 2) NOT NULL, `beginAt` DATETIME NOT NULL, `price` int NOT NULL, `hall_id` int NOT NULL, `trainer_id` int NOT NULL, PRIMARY KEY (`id`), INDEX `fk_class_hall1_idx`(`hall_id` ASC) VISIBLE, INDEX `fk_class_trainer1_idx`(`trainer_id` ASC) VISIBLE, CONSTRAINT `fk_class_hall1` FOREIGN KEY (`hall_id`) REFERENCES `mydb`.`hall`(`id`
) ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT `fk_class_trainer1` FOREIGN KEY (`trainer_id`) REFERENCES `mydb`.`trainer`(`id`
) ON DELETE NO ACTION ON UPDATE NO ACTION) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`sign_for_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_center`.`sign_for_class`(`id` int NOT NULL AUTO_INCREMENT, `client_id` int NOT NULL, `class_id` int NOT NULL, `date` DATETIME NOT NULL, PRIMARY KEY (`id`), INDEX `fk_sign_for_class_client1_idx`(`client_id` ASC) VISIBLE, INDEX `fk_sign_for_class_class1_idx`(`class_id` ASC) VISIBLE, CONSTRAINT `fk_sign_for_class_client1` FOREIGN KEY (`client_id`) REFERENCES `mydb`.`client`(`id`
) ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT `fk_sign_for_class_class1` FOREIGN KEY (`class_id`) REFERENCES `mydb`.`class`(`id`
) ON DELETE NO ACTION ON UPDATE NO ACTION) ENGINE = InnoDB;

SET SQL_MODE = @OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

